// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.543
package views

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

func Komponents() templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<!doctype html><html lang=\"en-US\"><head><meta charset=\"UTF-8\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"><link href=\"static/output.css\" rel=\"stylesheet\"><title>Komponente</title></head><body class=\"relative m-auto max-w-md top-2 h-screen bg-gradient-to-br from-sky-200 via-emerald-200 to-amber-100\"><div class=\"absolute w-96 h-60 bg-slate-500\"><a href=\"/\" class=\"absolute top-20 w-28 left-4 bg-red-500\"><img src=\"static/vezbamo_logo6.svg\" height=\"25\" width=\"25\">imageeeeeeeeeeeeeee</a><div class=\"relative w-40 h-20 bg-blue-500\">blue<div class=\"absolute w-30 h-10 bg-green-300\">green child</div></div><div class=\"relative top-40 w-20 h-10 bg-green-900\">green parent too long for boxxxxx</div></div><div class=\"relative top-72 w-96 h-60 bg-lime-300\"><a href=\"/\" class=\"absolute top-20 w-28 left-4 bg-red-500\"><img src=\"static/vezbamo_logo6.svg\" height=\"25\" width=\"25\">imaggggg</a><div class=\"absolute w-40 h-20 bg-blue-500\">rel blue<div class=\"absolute w-30 h-10 bg-green-300\">rel green child</div></div><div class=\"absolute top-40 w-20 h-10 bg-green-900\">green parent too long going out</div></div><!--\n\n    \n\n    --></body></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
