// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.747
package views

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Komponents() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<!doctype html><html lang=\"en-US\"><head><meta charset=\"UTF-8\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"><link href=\"static/output.css\" rel=\"stylesheet\"><title>Komponente</title></head><body class=\"relative max-w-md bg-gradient-to-br from-sky-300 to-gray-500\"><div class=\"relative left-10 w-96 h-60 bg-slate-500\"><a href=\"/\" class=\"absolute bottom-7 right-7 w-28 bg-red-500\"><img class=\"static top-4 left-5\" src=\"static/site/vezbamo_logo6.svg\" height=\"25\" width=\"25\"> imageeeeeee4</a><div class=\"static w-40 h-20 bg-blue-500\">blue parent<div class=\"static w-30 h-10 bg-green-300\">green child</div></div><div class=\"absolute left-10 top-10 w-20 h-10 bg-green-900\">green parent too long for boxxxxx</div><div class=\"fixed right-0 top-0 w-20 h-20 bg-green-500\">greeeeeen</div></div><div class=\"static top-10 right-9 w-md h-60 bg-lime-300\"><a href=\"/\" class=\"static top-32 w-28 left-4 bg-red-500\"><img class=\"static top-4\" src=\"static/site/vezbamo_logo6.svg\" height=\"25\" width=\"25\">imaggggg</a><div class=\"static w-40 h-20 bg-blue-500\">rel blue parent<div class=\"static w-30 h-10 bg-green-300\">rel green child</div></div><div class=\"static left-32 top-36 w-20 h-10 bg-green-900\">green parent too long going out</div></div><!--\n\n    \n\n    --></body></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return templ_7745c5c3_Err
	})
}
