package models

import (
	"time"
)

type DB struct{}

type User struct {
	U_id                 int       `db:"u_id"`
	Created_at_time      time.Time `db:"created_at_time"`
	Hash_lozinka         string    `db:"hash_lozinka"`
	Email                string    `db:"email"`
	User_name            string    `db:"user_name"`
	Mode                 string    `db:"user_mode"`
	Level                string    `db:"user_level"`
	Basic                bool      `db:"basic"`
	Js                   bool      `db:"js"`
	C                    bool      `db:"c"`
	Payment_date         time.Time `db:"payment_date"`
	Payment_expire       time.Time `db:"payment_expire"`
	Payment_amount       int       `db:"payment_amount"`
	Payment_currency     string    `db:"payment_currency"`
	Verified_email       string    `db:"verified_email"`
	Last_sign_in_time    time.Time `db:"last_sign_in_time"`
	Last_sign_in_headers string    `db:"last_sign_in_headers"`
	Created_at_headers   string    `db:"created_at_headers"`
	Deleted_at           time.Time `db:"deleted_at"`
	Bad_sign_in_attempts int       `db:"bad_sign_in_attempts"`
	Bad_sign_in_time     time.Time `db:"bad_sign_in_time"`
	Updated_at           time.Time `db:"updated_at"`
}

type Settings struct {
	S_id                       int       `db:"s_id"`
	Updated_at                 time.Time `db:"updated_at"`
	Bad_sign_in_attempts_limit string    `db:"bad_sign_in_attempts_limit"`
	Bad_sign_in_time_limit     string    `db:"bad_sign_in_time_limit"`
	Same_ip_sign_up_time_limit string    `db:"same_ip_sign_up_time_limit"`
}

type Billing struct {
	Id                 int32     `db:"id"`
	Client_id          int       `db:"client_id"`
	Client_name        string    `db:"client_name"`
	Messages_sent      int       `db:"messages_sent"`
	Charge_per_message float32   `db:"charge_per_message"`
	Sms_cost           float32   `db:"sms_cost"`
	Create_time        time.Time `db:"create_time"`
}

type Note struct {
	B_id        int       `db:"b_id"`
	Ime_tag     string    `db:"ime_tag"`
	Mejl        string    `db:"mejl"`
	Tema        string    `db:"tema"`
	Poruka      string    `db:"poruka"`
	User_id     string    `db:"user_id"`
	User_mail   string    `db:"user_mail"`
	From_url    string    `db:"from_url"`
	Datum_upisa time.Time `db:"datum_upisa"`
}

type Test struct {
	G_id             int    `db:"g_id"`
	Tip              string `db:"tip"`
	Obrazovni_profil any    `db:"obrazovni_profil"`
	Razred           any    `db:"razred"`
	Predmet          any    `db:"predmet"`
	Oblast           string `db:"oblast"`
	Link1            any    `db:"link1"`
	Link2            any    `db:"link2"`
	Link3            any    `db:"link3"`
	User_id          any    `db:"user_id"`
	From_url         any    `db:"from_url"`
	Datum_upisa      any    `db:"datum_upisa"`
	Pitanje_1        any    `db:"pitanje_1"`
	Odg_1_1          any    `db:"odg_1_1"`
	Odg_1_2          any    `db:"odg_1_2"`
	Odg_1_3          any    `db:"odg_1_3"`
	Odg_1_4          any    `db:"odg_1_4"`
	R_1              any    `db:"r_1"`
	Pitanje_2        any    `db:"pitanje_2"`
	Odg_2_1          any    `db:"odg_2_1"`
	Odg_2_2          any    `db:"odg_2_2"`
	Odg_2_3          any    `db:"odg_2_3"`
	Odg_2_4          any    `db:"odg_2_4"`
	R_2              any    `db:"r_2"`
	Pitanje_3        any    `db:"pitanje_3"`
	Odg_3_1          any    `db:"odg_3_1"`
	Odg_3_2          any    `db:"odg_3_2"`
	Odg_3_3          any    `db:"odg_3_3"`
	Odg_3_4          any    `db:"odg_3_4"`
	R_3              any    `db:"r_3"`
	Pitanje_4        any    `db:"pitanje_4"`
	Odg_4_1          any    `db:"odg_4_1"`
	Odg_4_2          any    `db:"odg_4_2"`
	Odg_4_3          any    `db:"odg_4_3"`
	Odg_4_4          any    `db:"odg_4_4"`
	R_4              any    `db:"r_4"`
	Pitanje_5        any    `db:"pitanje_5"`
	Odg_5_1          any    `db:"odg_5_1"`
	Odg_5_2          any    `db:"odg_5_2"`
	Odg_5_3          any    `db:"odg_5_3"`
	Odg_5_4          any    `db:"odg_5_4"`
	R_5              any    `db:"r_5"`
	Pitanje_6        any    `db:"pitanje_6"`
	Odg_6_1          any    `db:"odg_6_1"`
	Odg_6_2          any    `db:"odg_6_2"`
	Odg_6_3          any    `db:"odg_6_3"`
	Odg_6_4          any    `db:"odg_6_4"`
	R_6              any    `db:"r_6"`
	Pitanje_7        any    `db:"pitanje_7"`
	Odg_7_1          any    `db:"odg_7_1"`
	Odg_7_2          any    `db:"odg_7_2"`
	Odg_7_3          any    `db:"odg_7_3"`
	Odg_7_4          any    `db:"odg_7_4"`
	R_7              any    `db:"r_7"`
	Pitanje_8        any    `db:"pitanje_8"`
	Odg_8_1          any    `db:"odg_8_1"`
	Odg_8_2          any    `db:"odg_8_2"`
	Odg_8_3          any    `db:"odg_8_3"`
	Odg_8_4          any    `db:"odg_8_4"`
	R_8              any    `db:"r_8"`
	Pitanje_9        any    `db:"pitanje_9"`
	Odg_9_1          any    `db:"odg_9_1"`
	Odg_9_2          any    `db:"odg_9_2"`
	Odg_9_3          any    `db:"odg_9_3"`
	Odg_9_4          any    `db:"odg_9_4"`
	R_9              any    `db:"r_9"`
	Pitanje_10       any    `db:"pitanje_10"`
	Odg_10_1         any    `db:"odg_10_1"`
	Odg_10_2         any    `db:"odg_10_2"`
	Odg_10_3         any    `db:"odg_10_3"`
	Odg_10_4         any    `db:"odg_10_4"`
	R_10             any    `db:"r_10"`
	Pitanje_11       any    `db:"pitanje_11"`
	Odg_11_1         any    `db:"odg_11_1"`
	Odg_11_2         any    `db:"odg_11_2"`
	Odg_11_3         any    `db:"odg_11_3"`
	Odg_11_4         any    `db:"odg_11_4"`
	R_11             any    `db:"r_11"`
	Pitanje_12       any    `db:"pitanje_12"`
	Odg_12_1         any    `db:"odg_12_1"`
	Odg_12_2         any    `db:"odg_12_2"`
	Odg_12_3         any    `db:"odg_12_3"`
	Odg_12_4         any    `db:"odg_12_4"`
	R_12             any    `db:"r_12"`
	Pitanje_13       any    `db:"pitanje_13"`
	Odg_13_1         any    `db:"odg_13_1"`
	Odg_13_2         any    `db:"odg_13_2"`
	Odg_13_3         any    `db:"odg_13_3"`
	Odg_13_4         any    `db:"odg_13_4"`
	R_13             any    `db:"r_13"`
	Pitanje_14       any    `db:"pitanje_14"`
	Odg_14_1         any    `db:"odg_14_1"`
	Odg_14_2         any    `db:"odg_14_2"`
	Odg_14_3         any    `db:"odg_14_3"`
	Odg_14_4         any    `db:"odg_14_4"`
	R_14             any    `db:"r_14"`
	Pitanje_15       any    `db:"pitanje_15"`
	Odg_15_1         any    `db:"odg_15_1"`
	Odg_15_2         any    `db:"odg_15_2"`
	Odg_15_3         any    `db:"odg_15_3"`
	Odg_15_4         any    `db:"odg_15_4"`
	R_15             any    `db:"r_15"`
	Pitanje_16       any    `db:"pitanje_16"`
	Odg_16_1         any    `db:"odg_16_1"`
	Odg_16_2         any    `db:"odg_16_2"`
	Odg_16_3         any    `db:"odg_16_3"`
	Odg_16_4         any    `db:"odg_16_4"`
	R_16             any    `db:"r_16"`
	Pitanje_17       any    `db:"pitanje_17"`
	Odg_17_1         any    `db:"odg_17_1"`
	Odg_17_2         any    `db:"odg_17_2"`
	Odg_17_3         any    `db:"odg_17_3"`
	Odg_17_4         any    `db:"odg_17_4"`
	R_17             any    `db:"r_17"`
	Pitanje_18       any    `db:"pitanje_18"`
	Odg_18_1         any    `db:"odg_18_1"`
	Odg_18_2         any    `db:"odg_18_2"`
	Odg_18_3         any    `db:"odg_18_3"`
	Odg_18_4         any    `db:"odg_18_4"`
	R_18             any    `db:"r_18"`
	Pitanje_19       any    `db:"pitanje_19"`
	Odg_19_1         any    `db:"odg_19_1"`
	Odg_19_2         any    `db:"odg_19_2"`
	Odg_19_3         any    `db:"odg_19_3"`
	Odg_19_4         any    `db:"odg_19_4"`
	R_19             any    `db:"r_19"`
	Pitanje_20       any    `db:"pitanje_20"`
	Odg_20_1         any    `db:"odg_20_1"`
	Odg_20_2         any    `db:"odg_20_2"`
	Odg_20_3         any    `db:"odg_20_3"`
	Odg_20_4         any    `db:"odg_20_4"`
	R_20             any    `db:"r_20"`
	Pitanje_21       any    `db:"pitanje_21"`
	Odg_21_1         any    `db:"odg_21_1"`
	Odg_21_2         any    `db:"odg_21_2"`
	Odg_21_3         any    `db:"odg_21_3"`
	Odg_21_4         any    `db:"odg_21_4"`
	R_21             any    `db:"r_21"`
	Pitanje_22       any    `db:"pitanje_22"`
	Odg_22_1         any    `db:"odg_22_1"`
	Odg_22_2         any    `db:"odg_22_2"`
	Odg_22_3         any    `db:"odg_22_3"`
	Odg_22_4         any    `db:"odg_22_4"`
	R_22             any    `db:"r_22"`
	Pitanje_23       any    `db:"pitanje_23"`
	Odg_23_1         any    `db:"odg_23_1"`
	Odg_23_2         any    `db:"odg_23_2"`
	Odg_23_3         any    `db:"odg_23_3"`
	Odg_23_4         any    `db:"odg_23_4"`
	R_23             any    `db:"r_23"`
	Pitanje_24       any    `db:"pitanje_24"`
	Odg_24_1         any    `db:"odg_24_1"`
	Odg_24_2         any    `db:"odg_24_2"`
	Odg_24_3         any    `db:"odg_24_3"`
	Odg_24_4         any    `db:"odg_24_4"`
	R_24             any    `db:"r_24"`
	Pitanje_25       any    `db:"pitanje_25"`
	Odg_25_1         any    `db:"odg_25_1"`
	Odg_25_2         any    `db:"odg_25_2"`
	Odg_25_3         any    `db:"odg_25_3"`
	Odg_25_4         any    `db:"odg_25_4"`
	R_25             any    `db:"r_25"`
	Pitanje_26       any    `db:"pitanje_26"`
	Odg_26_1         any    `db:"odg_26_1"`
	Odg_26_2         any    `db:"odg_26_2"`
	Odg_26_3         any    `db:"odg_26_3"`
	Odg_26_4         any    `db:"odg_26_4"`
	R_26             any    `db:"r_26"`
	Pitanje_27       any    `db:"pitanje_27"`
	Odg_27_1         any    `db:"odg_27_1"`
	Odg_27_2         any    `db:"odg_27_2"`
	Odg_27_3         any    `db:"odg_27_3"`
	Odg_27_4         any    `db:"odg_27_4"`
	R_27             any    `db:"r_27"`
	Pitanje_28       any    `db:"pitanje_28"`
	Odg_28_1         any    `db:"odg_28_1"`
	Odg_28_2         any    `db:"odg_28_2"`
	Odg_28_3         any    `db:"odg_28_3"`
	Odg_28_4         any    `db:"odg_28_4"`
	R_28             any    `db:"r_28"`
	Pitanje_29       any    `db:"pitanje_29"`
	Odg_29_1         any    `db:"odg_29_1"`
	Odg_29_2         any    `db:"odg_29_2"`
	Odg_29_3         any    `db:"odg_29_3"`
	Odg_29_4         any    `db:"odg_29_4"`
	R_29             any    `db:"r_29"`
	Pitanje_30       any    `db:"pitanje_30"`
	Odg_30_1         any    `db:"odg_30_1"`
	Odg_30_2         any    `db:"odg_30_2"`
	Odg_30_3         any    `db:"odg_30_3"`
	Odg_30_4         any    `db:"odg_30_4"`
	R_30             any    `db:"r_30"`
}
type Test2 struct {
	G_id             int8      `db:"g_id"`
	Tip              string    `db:"tip"`
	Obrazovni_profil string    `db:"obrazovni_profil"`
	Razred           string    `db:"razred"`
	Predmet          string    `db:"predmet"`
	Oblast           string    `db:"oblast"`
	Link1            string    `db:"link1"`
	Link2            string    `db:"link2"`
	Link3            string    `db:"link3"`
	User_id          string    `db:"user_id"`
	From_url         string    `db:"from_url"`
	Datum_upisa      time.Time `db:"datum_upisa"`
	Pitanje_1        string    `db:"pitanje_1"`
	Odg_1_1          string    `db:"odg_1_1"`
	Odg_1_2          string    `db:"odg_1_2"`
	Odg_1_3          string    `db:"odg_1_3"`
	Odg_1_4          string    `db:"odg_1_4"`
	R_1              string    `db:"r_1"`
	Pitanje_2        string    `db:"pitanje_2"`
	Odg_2_1          string    `db:"odg_2_1"`
	Odg_2_2          string    `db:"odg_2_2"`
	Odg_2_3          string    `db:"odg_2_3"`
	Odg_2_4          string    `db:"odg_2_4"`
	R_2              string    `db:"r_2"`
	Pitanje_3        string    `db:"pitanje_3"`
	Odg_3_1          string    `db:"odg_3_1"`
	Odg_3_2          string    `db:"odg_3_2"`
	Odg_3_3          string    `db:"odg_3_3"`
	Odg_3_4          string    `db:"odg_3_4"`
	R_3              string    `db:"r_3"`
	Pitanje_4        string    `db:"pitanje_4"`
	Odg_4_1          string    `db:"odg_4_1"`
	Odg_4_2          string    `db:"odg_4_2"`
	Odg_4_3          string    `db:"odg_4_3"`
	Odg_4_4          string    `db:"odg_4_4"`
	R_4              string    `db:"r_4"`
	Pitanje_5        string    `db:"pitanje_5"`
	Odg_5_1          string    `db:"odg_5_1"`
	Odg_5_2          string    `db:"odg_5_2"`
	Odg_5_3          string    `db:"odg_5_3"`
	Odg_5_4          string    `db:"odg_5_4"`
	R_5              string    `db:"r_5"`
	Pitanje_6        string    `db:"pitanje_6"`
	Odg_6_1          string    `db:"odg_6_1"`
	Odg_6_2          string    `db:"odg_6_2"`
	Odg_6_3          string    `db:"odg_6_3"`
	Odg_6_4          string    `db:"odg_6_4"`
	R_6              string    `db:"r_6"`
	Pitanje_7        string    `db:"pitanje_7"`
	Odg_7_1          string    `db:"odg_7_1"`
	Odg_7_2          string    `db:"odg_7_2"`
	Odg_7_3          string    `db:"odg_7_3"`
	Odg_7_4          string    `db:"odg_7_4"`
	R_7              string    `db:"r_7"`
	Pitanje_8        string    `db:"pitanje_8"`
	Odg_8_1          string    `db:"odg_8_1"`
	Odg_8_2          string    `db:"odg_8_2"`
	Odg_8_3          string    `db:"odg_8_3"`
	Odg_8_4          string    `db:"odg_8_4"`
	R_8              string    `db:"r_8"`
	Pitanje_9        string    `db:"pitanje_9"`
	Odg_9_1          string    `db:"odg_9_1"`
	Odg_9_2          string    `db:"odg_9_2"`
	Odg_9_3          string    `db:"odg_9_3"`
	Odg_9_4          string    `db:"odg_9_4"`
	R_9              string    `db:"r_9"`
	Pitanje_10       string    `db:"pitanje_10"`
	Odg_10_1         string    `db:"odg_10_1"`
	Odg_10_2         string    `db:"odg_10_2"`
	Odg_10_3         string    `db:"odg_10_3"`
	Odg_10_4         string    `db:"odg_10_4"`
	R_10             string    `db:"r_10"`
	Pitanje_11       string    `db:"pitanje_11"`
	Odg_11_1         string    `db:"odg_11_1"`
	Odg_11_2         string    `db:"odg_11_2"`
	Odg_11_3         string    `db:"odg_11_3"`
	Odg_11_4         string    `db:"odg_11_4"`
	R_11             string    `db:"r_11"`
	Pitanje_12       string    `db:"pitanje_12"`
	Odg_12_1         string    `db:"odg_12_1"`
	Odg_12_2         string    `db:"odg_12_2"`
	Odg_12_3         string    `db:"odg_12_3"`
	Odg_12_4         string    `db:"odg_12_4"`
	R_12             string    `db:"r_12"`
	Pitanje_13       string    `db:"pitanje_13"`
	Odg_13_1         string    `db:"odg_13_1"`
	Odg_13_2         string    `db:"odg_13_2"`
	Odg_13_3         string    `db:"odg_13_3"`
	Odg_13_4         string    `db:"odg_13_4"`
	R_13             string    `db:"r_13"`
	Pitanje_14       string    `db:"pitanje_14"`
	Odg_14_1         string    `db:"odg_14_1"`
	Odg_14_2         string    `db:"odg_14_2"`
	Odg_14_3         string    `db:"odg_14_3"`
	Odg_14_4         string    `db:"odg_14_4"`
	R_14             string    `db:"r_14"`
	Pitanje_15       string    `db:"pitanje_15"`
	Odg_15_1         string    `db:"odg_15_1"`
	Odg_15_2         string    `db:"odg_15_2"`
	Odg_15_3         string    `db:"odg_15_3"`
	Odg_15_4         string    `db:"odg_15_4"`
	R_15             string    `db:"r_15"`
	Pitanje_16       string    `db:"pitanje_16"`
	Odg_16_1         string    `db:"odg_16_1"`
	Odg_16_2         string    `db:"odg_16_2"`
	Odg_16_3         string    `db:"odg_16_3"`
	Odg_16_4         string    `db:"odg_16_4"`
	R_16             string    `db:"r_16"`
	Pitanje_17       string    `db:"pitanje_17"`
	Odg_17_1         string    `db:"odg_17_1"`
	Odg_17_2         string    `db:"odg_17_2"`
	Odg_17_3         string    `db:"odg_17_3"`
	Odg_17_4         string    `db:"odg_17_4"`
	R_17             string    `db:"r_17"`
	Pitanje_18       string    `db:"pitanje_18"`
	Odg_18_1         string    `db:"odg_18_1"`
	Odg_18_2         string    `db:"odg_18_2"`
	Odg_18_3         string    `db:"odg_18_3"`
	Odg_18_4         string    `db:"odg_18_4"`
	R_18             string    `db:"r_18"`
	Pitanje_19       string    `db:"pitanje_19"`
	Odg_19_1         string    `db:"odg_19_1"`
	Odg_19_2         string    `db:"odg_19_2"`
	Odg_19_3         string    `db:"odg_19_3"`
	Odg_19_4         string    `db:"odg_19_4"`
	R_19             string    `db:"r_19"`
	Pitanje_20       string    `db:"pitanje_20"`
	Odg_20_1         string    `db:"odg_20_1"`
	Odg_20_2         string    `db:"odg_20_2"`
	Odg_20_3         string    `db:"odg_20_3"`
	Odg_20_4         string    `db:"odg_20_4"`
	R_20             string    `db:"r_20"`
	Pitanje_21       string    `db:"pitanje_21"`
	Odg_21_1         string    `db:"odg_21_1"`
	Odg_21_2         string    `db:"odg_21_2"`
	Odg_21_3         string    `db:"odg_21_3"`
	Odg_21_4         string    `db:"odg_21_4"`
	R_21             string    `db:"r_21"`
	Pitanje_22       string    `db:"pitanje_22"`
	Odg_22_1         string    `db:"odg_22_1"`
	Odg_22_2         string    `db:"odg_22_2"`
	Odg_22_3         string    `db:"odg_22_3"`
	Odg_22_4         string    `db:"odg_22_4"`
	R_22             string    `db:"r_22"`
	Pitanje_23       string    `db:"pitanje_23"`
	Odg_23_1         string    `db:"odg_23_1"`
	Odg_23_2         string    `db:"odg_23_2"`
	Odg_23_3         string    `db:"odg_23_3"`
	Odg_23_4         string    `db:"odg_23_4"`
	R_23             string    `db:"r_23"`
	Pitanje_24       string    `db:"pitanje_24"`
	Odg_24_1         string    `db:"odg_24_1"`
	Odg_24_2         string    `db:"odg_24_2"`
	Odg_24_3         string    `db:"odg_24_3"`
	Odg_24_4         string    `db:"odg_24_4"`
	R_24             string    `db:"r_24"`
	Pitanje_25       string    `db:"pitanje_25"`
	Odg_25_1         string    `db:"odg_25_1"`
	Odg_25_2         string    `db:"odg_25_2"`
	Odg_25_3         string    `db:"odg_25_3"`
	Odg_25_4         string    `db:"odg_25_4"`
	R_25             string    `db:"r_25"`
	Pitanje_26       string    `db:"pitanje_26"`
	Odg_26_1         string    `db:"odg_26_1"`
	Odg_26_2         string    `db:"odg_26_2"`
	Odg_26_3         string    `db:"odg_26_3"`
	Odg_26_4         string    `db:"odg_26_4"`
	R_26             string    `db:"r_26"`
	Pitanje_27       string    `db:"pitanje_27"`
	Odg_27_1         string    `db:"odg_27_1"`
	Odg_27_2         string    `db:"odg_27_2"`
	Odg_27_3         string    `db:"odg_27_3"`
	Odg_27_4         string    `db:"odg_27_4"`
	R_27             string    `db:"r_27"`
	Pitanje_28       string    `db:"pitanje_28"`
	Odg_28_1         string    `db:"odg_28_1"`
	Odg_28_2         string    `db:"odg_28_2"`
	Odg_28_3         string    `db:"odg_28_3"`
	Odg_28_4         string    `db:"odg_28_4"`
	R_28             string    `db:"r_28"`
	Pitanje_29       string    `db:"pitanje_29"`
	Odg_29_1         string    `db:"odg_29_1"`
	Odg_29_2         string    `db:"odg_29_2"`
	Odg_29_3         string    `db:"odg_29_3"`
	Odg_29_4         string    `db:"odg_29_4"`
	R_29             string    `db:"r_29"`
	Pitanje_30       string    `db:"pitanje_30"`
	Odg_30_1         string    `db:"odg_30_1"`
	Odg_30_2         string    `db:"odg_30_2"`
	Odg_30_3         string    `db:"odg_30_3"`
	Odg_30_4         string    `db:"odg_30_4"`
	R_30             string    `db:"r_30"`
}
